config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  root 'homepages#index'

  resources :educations
  resources :experiences
  resources :dashboards
  resources :templates
  resources :homepages
  resources :template_viewers

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :templates, dependent: :destroy
  validates_presence_of :first_name, :date_of_birth

end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :school_name, :school_address

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :company_name, :job_title, :start_date
end

app/models/template.rb
class Template < ActiveRecord::Base
  has_attached_file :html_file
  has_attached_file :css_file
  
  validates_presence_of :template_theme_name
  validates_attachment_presence :html_file

  validates_attachment_content_type :html_file, content_type: /text\/html/
  validates_attachment_content_type :css_file, content_type: /text\/css/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :educations, dependent: :destroy
  has_many :experiences, dependent: :destroy
  validates_presence_of :first_name, :date_of_birth, :postal_code, :country

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller? && resource_name == :user
      "users"
    elsif devise_controller? && resource_name == :admin
      "admins"
    else
      "application"
    end
  end

  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    elsif resource_class == Admin
      Admin::ParameterSanitizer.new(Admin, :admin, params)
    else
      super # Use the default one
    end
  end
  
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      return dashboards_path
    elsif resource_or_scope == :user
      return homepages_path
    end
    
  end
  
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  
  layout 'dashboards'
  
  before_action :authenticate_admin!

  def index
    @templates = Template.where(admin_id: current_admin.id)
  end

end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController

  def index
    @edus = Education.all

  end

  def new
    @edu = Education.new
  end

  def create
    @edu = Education.new(new_education_param)
    @edu.user_id = current_user.id
    Rails.logger.info ">>>>>>>>>>>>>>>>> #{@edu.inspect}"

    if user_signed_in? && @edu.save
      redirect_to homepages_path
    else
      Rails.logger.info ">>>>>>>>>>>>>> #{@edu.errors.inspect}"
      render action: 'new'
    end

  end

  def edit
    @edu = Education.find(find_education_param)
  end

  def update
    @edu = Education.find(find_education_param)
    if @edu.update_attributes(update_education_param)
      redirect_to homepages_path
    else
      render action: 'edit'
    end
  end

  def destroy
    @edu = Education.find(find_education_param)

    @edu.delete
    redirect_to homepages_path
  end



  private

  def new_education_param
    params.require(:education).permit(:school_name, :school_address)
  end

  def update_education_param
    params.require(:education).permit(:school_name, :school_address)
  end

  def find_education_param
    params.require(:id)
  end


end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController

  def index
    @exps = Experience.all
  end

  def new
    @exp = Experience.new
  end

  def create
    @exp = Experience.new(new_experience_params)
    @exp.user_id = current_user.id
    
    if user_signed_in? && @exp.save
      redirect_to homepages_path
    else
      render action: 'new'
    end
  end

  def edit
    @exp = Experience.find(find_experience_params)
  end

  def update
    @exp = Experience.find(find_experience_params)

    if @exp.update_attributes(new_experience_params)
      redirect_to homepages_path
    else
      render action: 'edit'
    end
  end

  def destroy
    @exp = Experience.find(find_experience_params)

    @exp.delete
    redirect_to action: homepages_path
  end


  private

  def new_experience_params
    params.require(:experience).permit(:company_name, :job_title, :start_date, :end_date)
  end

  def find_experience_params
    params.require(:id)
  end

end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @educations = Education.where(user_id: current_user.id)
    @experiences = Experience.where(user_id: current_user.id)
  end
  
end

app/controllers/template_viewers_controller.rb
class TemplateViewersController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @templates = Template.all
    @educations = Education.where(user_id: current_user.id)
    @experiences = Experience.where(user_id: current_user.id)
  end
  
end

app/controllers/templates_controller.rb
class TemplatesController < DashboardsController

  before_action :authenticate_admin!

  def new
    @template = Template.new
  end

  def create
    @template = Template.new(new_template_params)
    @template.admin_id = current_admin.id

    if admin_signed_in? && @template.save
      redirect_to dashboards_path
    else
      render action: 'new'
    end
  end

  def edit
    @template = Template.find(find_template_params)
  end

  def update
    @template = Template.find(find_template_params)

    if @template.update_attributes(new_template_params)
      redirect_to dashboards_path
    else
      render action: 'edit'
    end
  end

  def destroy
    @template = Template.find(find_template_params)

    @template.html_file = nil
    @template.css_file = nil
    @template.delete

    redirect_to dashboards_path
  end

  private

  def new_template_params
    params.require(:template).permit(:template_theme_name, :html_file, :css_file)
  end

  def find_template_params
    params.require(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up as admin", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/dashboards/index.html.erb
<div class="col-md-12">

  <h1 class="text-center">Templates</h1>

  <table class="table table-bordered table-hover table-responsive table-condensed">
    <thead>
    <tr>
      <td><strong>ID</strong></td>
      <td><strong>Template Theme</strong></td>
      <td><strong>HTML File Path</strong></td>
      <td><strong>CSS File Path</strong></td>
    </tr>
    </thead>
    <tbody>
    <% @templates.each do |t| %>
        <tr>
          <td><%= t.id %></td>
          <td><%= t.template_theme_name %></td>
          <td><%= t.html_file %></td>
          <td><%= t.css_file %></td>
          <td><%= link_to "Modify", edit_template_path(t), class: 'btn btn-info' %>&nbsp;<%= link_to "Delete", template_path(t), method: :delete, class: 'btn btn-danger' %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <%= link_to 'Add New Template', new_template_path, class: 'btn btn-success'%>

</div>

app/views/educations/create.html.erb
<h1>new education created!</h1>

app/views/educations/edit.html.erb
<h1 class="text-center">Edit Education</h1>

<% if @edu.errors.any? %>
    <% @edu.errors.full_messages.each do |msg| %>
        <div class="text-danger text-center"><strong><%= msg %></strong></div>
    <% end %>
<% end %>
<br/>
<div class="col-md-12">
  <%= form_for @edu, html:{class: 'form-horizontal'} do |f| %>
      <div class="form-group">
        <div class="col-md-2 control-label"><label>School Name</label></div>
        <div class="col-md-10"><%= f.text_field :school_name, class: 'form-control' %></div>
      </div>
      <div class="form-group">
        <div class="col-md-2 control-label"><label>School Address</label></div>
        <div class="col-md-10"><%= f.text_field :school_address, class: 'form-control'%></div>
      </div>
      <br/>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10"><%= f.submit "Update Education", class: 'btn btn-success' %></div>
      </div>
  <% end %>
</div>

app/views/educations/index.html.erb
<div class="col-md-12">

    <h1 class="text-center">Educations</h1>

    <table class="table table-bordered table-hover table-responsive table-condensed">
        <thead>
            <tr>
              <td><strong>ID</strong></td>
              <td><strong>School Name</strong></td>
              <td><strong>School Address</strong></td>
            </tr>
        </thead>
        <tbody>
            <% @edus.each do |e| %>
              <tr>
                <td><%= e.id %></td>
                <td><%= e.school_name %></td>
                <td><%= e.school_address %></td>
                <td><%= link_to "Modify", edit_education_path(e), class: 'btn btn-info' %>&nbsp;<%= link_to "Delete", education_path(e), method: :delete, class: 'btn btn-danger' %></td>
              </tr>
            <% end %>
        </tbody>
    </table>

    <%= link_to "Add Education Info", new_education_path, class: 'btn btn-success' %>

</div>

app/views/educations/new.html.erb
<h1 class="text-center">New Education</h1>

<% if @edu.errors.any? %>
    <% @edu.errors.full_messages.each do |msg| %>
        <div class="text-danger text-center"><strong><%= msg %></strong></div>
    <% end %>
<% end %>
<br/>
<div class="col-md-12">
<%= form_for @edu, html:{class: 'form-horizontal'} do |f| %>
    <div class="form-group">
      <div class="col-md-2 control-label"><label>School Name</label></div>
      <div class="col-md-10"><%= f.text_field :school_name, class: 'form-control', placeholder: 'Name' %></div>
    </div>
    <div class="form-group">
      <div class="col-md-2 control-label"><label>School Address</label></div>
      <div class="col-md-10"><%= f.text_field :school_address, class: 'form-control', placeholder: 'Address' %></div>
    </div>
    <br/>
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10"><%= f.submit "Submit", class: 'btn btn-success' %></div>
    </div>
<% end %>
</div>

app/views/experiences/edit.html.erb
<h1 class="text-center">Edit Experience</h1>

<% if @exp.errors.any? %>
    <% @exp.errors.full_messages.each do |msg| %>
        <div class="text-danger text-center"><strong><%= msg %></strong></div>
    <% end %>
<% end %>
<br/>
<div class="col-md-12">
  <%= form_for @exp, html:{class: 'form-horizontal'} do |e| %>
      <div class="form-group">
        <div class="col-md-2 control-label"><label>Company Name</label></div>
        <div class="col-md-10"><%= e.text_field :company_name, class: 'form-control', placeholder: 'Your Company' %></div>
      </div>
      <div class="form-group">
        <div class="col-md-2 control-label"><label>Job Title</label></div>
        <div class="col-md-10"><%= e.text_field :job_title, class: 'form-control', placeholder: 'Your Job Title' %></div>
      </div>
      <div class="form-group">
        <div class="col-md-2 control-label"><label>Start Date (DD/MM/YYYY)</label></div>
        <div class="col-md-10"><%= e.date_field :start_date, class: 'form-control', placeholder: 'Start Date' %></div>
      </div>
      <div class="form-group">
        <div class="col-md-2 control-label"><label>End Date (DD/MM/YYYY)</label></div>
        <div class="col-md-10"><%= e.date_field :end_date, class: 'form-control', placeholder: 'End Date' %></div>
      </div>
      <br/>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10"><%= e.submit "Save Changes", class: 'btn btn-success' %></div>
      </div>
  <% end %>
</div>

app/views/experiences/index.html.erb
<div class="col-md-12">

  <h1 class="text-center">Experiences</h1>

  <table class="table table-bordered table-hover table-responsive table-condensed">
    <thead>
    <tr>
      <td><strong>ID</strong></td>
      <td><strong>Company Name</strong></td>
      <td><strong>Job Title</strong></td>
      <td><strong>Start Date</strong></td>
      <td><strong>End Date</strong></td>
    </tr>
    </thead>
    <tbody>
    <% @exps.each do |e| %>
        <tr>
          <td><%= e.id %></td>
          <td><%= e.company_name %></td>
          <td><%= e.job_title %></td>
          <td><%= e.start_date %></td>
          <td><%= e.end_date %></td>
          <td><%= link_to "Modify", edit_experience_path(e), class: 'btn btn-info' %>&nbsp;<%= link_to "Delete", experience_path(e), method: :delete, class: 'btn btn-danger' %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <%= link_to "Add Experience", new_experience_path, class: 'btn btn-success' %>

</div>

app/views/experiences/new.html.erb
<h1 class="text-center">New Experience</h1>

<% if @exp.errors.any? %>
    <% @exp.errors.full_messages.each do |msg| %>
        <div class="text-danger text-center"><strong><%= msg %></strong></div>
    <% end %>
<% end %>
<br/>
<div class="col-md-12">
  <%= form_for @exp, html:{class: 'form-horizontal'} do |e| %>
      <div class="form-group">
        <div class="col-md-2 control-label"><label>Company Name</label></div>
        <div class="col-md-10"><%= e.text_field :company_name, class: 'form-control', placeholder: 'Your Company' %></div>
      </div>
      <div class="form-group">
        <div class="col-md-2 control-label"><label>Job Title</label></div>
        <div class="col-md-10"><%= e.text_field :job_title, class: 'form-control', placeholder: 'Your Job Title' %></div>
      </div>
      <div class="form-group">
        <div class="col-md-2 control-label"><label>Start Date (DD/MM/YYYY)</label></div>
        <div class="col-md-10"><%= e.date_field :start_date, class: 'form-control', placeholder: 'Start Date' %></div>
      </div>
      <div class="form-group">
        <div class="col-md-2 control-label"><label>End Date (DD/MM/YYYY)</label></div>
        <div class="col-md-10"><%= e.date_field :end_date, class: 'form-control', placeholder: 'End Date' %></div>
      </div>
      <br/>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10"><%= e.submit "Add Experience", class: 'btn btn-success' %></div>
      </div>
  <% end %>
</div>

app/views/homepages/index.html.erb
<div class="col-md-12">

	<h2 class="text-center">Educations</h2>
  <%= link_to "Add Education", new_education_path, class: 'btn btn-success' %>
  <br></br>
	<table class="table table-bordered table-hover table-responsive table-condensed">
    <thead>
      <tr>
        <td><strong>ID</strong></td>
        <td><strong>School Name</strong></td>
        <td><strong>School Address</strong></td>
      </tr>
    </thead>
    <tbody>
      <% @educations.each do |e| %>
        <tr>
          <td><%= e.id %></td>
          <td><%= e.school_name %></td>
          <td><%= e.school_address %></td>
          <td>
            <div class='text-center'>
              <%= link_to "Modify", edit_education_path(e), class: 'btn btn-info' %>
            </div>
          </td>
          <td>
            <div class='text-center'>
              <%= link_to "Delete", education_path(e), method: :delete, class: 'btn btn-danger' %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br/>
  <hr>
  
  <h2 class="text-center">Experiences</h2>
  <%= link_to "Add Experience", new_experience_path, class: 'btn btn-success' %>
  <br></br>
  <table class="table table-bordered table-hover table-responsive table-condensed">
    <thead>
    <tr>
      <td><strong>ID</strong></td>
      <td><strong>Company Name</strong></td>
      <td><strong>Job Title</strong></td>
      <td><strong>Start Date</strong></td>
      <td><strong>End Date</strong></td>
    </tr>
    </thead>
    <tbody>
    <% @experiences.each do |e| %>
        <tr>
          <td><%= e.id %></td>
          <td><%= e.company_name %></td>
          <td><%= e.job_title %></td>
          <td><%= e.start_date %></td>
          <td><%= e.end_date %></td>
          <td>
            <div class='text-center'>
              <%= link_to "Modify", edit_experience_path(e), class: 'btn btn-info' %>
            </div>
          </td>
          <td>
            <div class='text-center'>
              <%= link_to "Delete", experience_path(e), method: :delete, class: 'btn btn-danger' %>
            </div>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
  
  <br/>
  
  <%= link_to "Proceed to Choose Template &#9658;".html_safe, template_viewers_path, class: 'pull-right btn btn-primary' %>

</div>

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mycv</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <%= link_to "MyCV Dashboard", dashboards_path, class: 'navbar-brand' %>
    </div>
    
    <div class='collapse navbar-collapse'>
      <p class="navbar-text">Submit Resume Template in 1, 2, 3!</p>
    
      <% if admin_signed_in? %>
        <form class="navbar-form navbar-right">
          <%= link_to "Logout", destroy_admin_session_path, method: :delete, class: 'btn btn-warning' %>
        </form>
        <form class="navbar-form navbar-right">
          <h5>Hello, <%= current_admin.first_name %> <%= current_admin.last_name %></h5>
        </form>
      <% end %>
    </div>
  </nav>
  
  <div class="col-md-12">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mycv</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <br/>
  <% if user_signed_in? %>
    <div class="col-md-12 nav">
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-warning pull-right' %>
    </div>
  <% end %>
<%= yield %>

</body>
</html>

app/views/layouts/dashboards.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mycv</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <br/>
  <% if user_signed_in? %>
    <div class="col-md-12 nav">
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-warning pull-right' %>
    </div>
  <% end %>

<%= yield %>


</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mycv</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <%= link_to "MyCV", homepages_path, class: 'navbar-brand' %>
    </div>
    
    <div class='collapse navbar-collapse'>
      <p class="navbar-text">Create Professional Resume in 1, 2, 3!</p>
    
      <% if user_signed_in? %>
        <form class="navbar-form navbar-right">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-warning' %>
        </form>
        <form class="navbar-form navbar-right">
          <h5>Hello, <%= current_user.first_name %> <%= current_user.last_name %></h5>
        </form>
      <% end %>
    </div>
  </nav>
  
  <div class="col-md-12">
    <%= yield %>
  </div>
</body>
</html>

app/views/template_viewers/index.html.erb
<h2 class='text-center'>Choose Your Resume Template</h2>

app/views/templates/edit.html.erb
<h1 class="text-center">Edit Templates</h1>

<% if @template.errors.any? %>
    <% @template.errors.full_messages.each do |msg| %>
        <div class="text-danger text-center"><h4><%= msg %></h4></div>
    <% end %>
<% end %>

<%= form_for @template, html: {multipart: true} do |f| %>
    <p>
      <%= f.label :template_theme_name , "Template Theme Name"%><br />
      <%= f.text_field :template_theme_name %>
    </p>

    <p>
      <%= f.label :html_file, "HTML file" %>
      <%= f.file_field :html_file %>
    </p>

    <p>
      <%= f.label :css_file, "CSS file"%>
      <%= f.file_field :css_file %>
    </p>

    <p><%= f.submit %></p>
<% end %>

app/views/templates/new.html.erb
<h1 class="text-center">New Templates</h1>

<% if @template.errors.any? %>
    <% @template.errors.full_messages.each do |msg| %>
        <div class="text-danger text-center"><h4><%= msg %></h4></div>
    <% end %>
<% end %>

<%= form_for @template, html: {multipart: true} do |f| %>
    <p>
      <%= f.label :template_theme_name , "Template Theme Name"%><br />
      <%= f.text_field :template_theme_name %>
    </p>

    <p>
      <%= f.label :html_file, "HTML file" %>
      <%= f.file_field :html_file %>
    </p>

    <p>
      <%= f.label :css_file, "CSS file" %>
      <%= f.file_field :css_file %>
    </p>

    <p><%= f.submit %></p>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>